SPOTIPY_CLIENT_ID = # spotify developer portal client_id
SPOTIPY_CLIENT_SECRET = # spotify developer portal client_secret_id
SPOTIPY_REDIRECT_URI = 'http://localhost:8888/callback'
SCOPE = "user-read-currently-playing"
MARKET = "TR"
api_id = # my.telegram.org app_id
api_hash = # my.telegram.org api_hash
token = # t.me/BotFather new bot token
chat = # telegram chat id t.me/ReWoxiSpotify
msg_id = # telegram message_id
